
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 17 2024 16:17:16 +07 (Mar 17 2024 09:17:16 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(rst, clk, flick, LEDs);
  input rst, clk, flick;
  output [15:0] LEDs;
  wire rst, clk, flick;
  wire [15:0] LEDs;
  wire [2:0] next_state;
  wire [2:0] current_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_2, n_3, n_4, n_5;
  wire n_6, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_75, n_91, n_92;
  TLATNXL \next_state_reg[2] (.GN (n_64), .D (n_53), .Q
       (next_state[2]), .QN (UNCONNECTED));
  TLATNXL \next_state_reg[1] (.GN (n_64), .D (n_62), .Q
       (next_state[1]), .QN (UNCONNECTED0));
  TLATNXL \next_state_reg[0] (.GN (n_64), .D (n_63), .Q
       (next_state[0]), .QN (n_5));
  OAI32X1 g1971__2398(.A0 (LEDs[5]), .A1 (current_state[1]), .A2
       (n_61), .B0 (n_49), .B1 (n_58), .Y (n_63));
  OAI211X1 g1976__5107(.A0 (n_28), .A1 (n_61), .B0 (n_50), .C0 (n_57),
       .Y (n_62));
  NOR4BX1 g1972__6260(.AN (n_54), .B (n_3), .C (n_56), .D (n_25), .Y
       (n_64));
  OAI2BB1X1 g1973__4319(.A0N (LEDs[1]), .A1N (n_4), .B0 (n_5), .Y
       (n_60));
  OAI2BB1X1 g1975__8428(.A0N (LEDs[1]), .A1N (next_state[0]), .B0
       (n_42), .Y (n_59));
  AOI2BB1X1 g1978__5526(.A0N (LEDs[0]), .A1N (n_52), .B0 (n_51), .Y
       (n_58));
  NAND3BXL g1979__6783(.AN (n_56), .B (n_47), .C (n_46), .Y (n_57));
  OAI2BB1X1 g1980__3680(.A0N (LEDs[15]), .A1N (n_43), .B0 (n_19), .Y
       (n_55));
  AOI22XL g1981__1617(.A0 (LEDs[15]), .A1 (current_state[2]), .B0
       (flick), .B1 (n_13), .Y (n_54));
  OAI31X1 g1977__2802(.A0 (n_52), .A1 (n_45), .A2 (n_61), .B0 (n_48),
       .Y (n_53));
  OAI32X1 g1989__1705(.A0 (current_state[1]), .A1 (current_state[2]),
       .A2 (n_29), .B0 (LEDs[5]), .B1 (n_26), .Y (n_51));
  DFFRX2 \LEDs_reg[11] (.RN (rst), .CK (clk), .D (n_44), .Q (LEDs[11]),
       .QN (UNCONNECTED1));
  DFFRHQX1 \LEDs_reg[1] (.RN (rst), .CK (clk), .D (n_32), .Q (LEDs[1]));
  OAI2BB1X1 g1990__5122(.A0N (n_49), .A1N (n_6), .B0
       (current_state[1]), .Y (n_50));
  AOI22XL g1991__8246(.A0 (current_state[2]), .A1 (n_92), .B0 (rst),
       .B1 (n_47), .Y (n_48));
  OAI2BB1X1 g1998__7098(.A0N (LEDs[11]), .A1N (n_30), .B0 (n_45), .Y
       (n_46));
  DFFRHQX1 \LEDs_reg[15] (.RN (rst), .CK (clk), .D (n_91), .Q
       (LEDs[15]));
  OAI2BB1X1 g1997__6131(.A0N (LEDs[12]), .A1N (n_43), .B0 (n_9), .Y
       (n_44));
  AOI21X1 g1999__1881(.A0 (LEDs[3]), .A1 (n_43), .B0 (n_23), .Y (n_42));
  OAI2BB1X1 g2000__5115(.A0N (LEDs[9]), .A1N (n_43), .B0 (n_14), .Y
       (n_41));
  OAI2BB1X1 g2001__7482(.A0N (LEDs[10]), .A1N (n_43), .B0 (n_22), .Y
       (n_40));
  OAI2BB1X1 g2002__4733(.A0N (LEDs[11]), .A1N (n_43), .B0 (n_21), .Y
       (n_39));
  OAI2BB1X1 g2005__6161(.A0N (LEDs[13]), .A1N (n_43), .B0 (n_15), .Y
       (n_38));
  OAI2BB1X1 g2011__9315(.A0N (LEDs[8]), .A1N (n_43), .B0 (n_11), .Y
       (n_37));
  OAI2BB1X1 g2004__9945(.A0N (LEDs[6]), .A1N (n_43), .B0 (n_18), .Y
       (n_36));
  OAI2BB1X1 g2007__2883(.A0N (LEDs[14]), .A1N (n_43), .B0 (n_20), .Y
       (n_35));
  OAI2BB1X1 g2008__2346(.A0N (LEDs[4]), .A1N (n_43), .B0 (n_10), .Y
       (n_34));
  OAI2BB1X1 g2009__1666(.A0N (LEDs[7]), .A1N (n_43), .B0 (n_17), .Y
       (n_33));
  OAI2BB1X1 g2010__7410(.A0N (LEDs[2]), .A1N (n_43), .B0 (n_24), .Y
       (n_32));
  OAI2BB1X1 g2006__6417(.A0N (LEDs[5]), .A1N (n_43), .B0 (n_16), .Y
       (n_31));
  AOI21XL g2021__5477(.A0 (n_12), .A1 (n_30), .B0 (n_29), .Y (n_45));
  OR2X1 g2022__2398(.A (current_state[2]), .B (n_56), .Y (n_61));
  OA22X1 g2023__5107(.A0 (n_30), .A1 (n_29), .B0 (n_2), .B1
       (current_state[1]), .Y (n_28));
  INVXL g2012(.A (n_47), .Y (n_26));
  ADDHX1 g2013__4319(.A (current_state[2]), .B (n_52), .CO (n_47), .S
       (n_25));
  AOI21X1 g2029__8428(.A0 (LEDs[0]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_24));
  AOI21X1 g2019__5526(.A0 (LEDs[8]), .A1 (n_75), .B0 (n_23), .Y (n_22));
  AOI21X1 g2020__6783(.A0 (LEDs[9]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_21));
  AOI21X1 g2024__3680(.A0 (LEDs[12]), .A1 (n_75), .B0 (n_23), .Y
       (n_20));
  AOI21X1 g2026__1617(.A0 (LEDs[13]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_19));
  AOI21X1 g2028__2802(.A0 (LEDs[4]), .A1 (n_75), .B0 (n_23), .Y (n_18));
  AOI21X1 g2018__1705(.A0 (LEDs[5]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_17));
  AOI21X1 g2025__5122(.A0 (LEDs[3]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_16));
  AOI21X1 g2031__8246(.A0 (LEDs[11]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_15));
  AOI21X1 g2017__7098(.A0 (LEDs[7]), .A1 (n_75), .B0 (n_23), .Y (n_14));
  OAI21XL g2036__6131(.A0 (LEDs[11]), .A1 (n_12), .B0 (n_30), .Y
       (n_13));
  AOI21X1 g2030__1881(.A0 (LEDs[6]), .A1 (next_state[0]), .B0 (n_23),
       .Y (n_11));
  AOI21X1 g2014__5115(.A0 (LEDs[2]), .A1 (n_75), .B0 (n_23), .Y (n_10));
  AOI21X1 g2016__7482(.A0 (LEDs[10]), .A1 (n_75), .B0 (n_23), .Y (n_9));
  INVXL g2032(.A (n_92), .Y (n_49));
  NAND2XL g2033__6161(.A (rst), .B (current_state[0]), .Y (n_56));
  NAND4XL g2015__9315(.A (flick), .B (LEDs[10]), .C (n_0), .D (rst), .Y
       (n_6));
  AND2X1 g2037__9945(.A (n_5), .B (n_4), .Y (n_43));
  AND3X1 g2038__2883(.A (next_state[2]), .B (next_state[1]), .C (n_75),
       .Y (n_23));
  NOR2XL g2042__2346(.A (n_12), .B (current_state[2]), .Y (n_3));
  OR2X1 g2044__1666(.A (LEDs[6]), .B (n_2), .Y (n_30));
  DFFRHQX1 \current_state_reg[0] (.RN (rst), .CK (clk), .D (n_75), .Q
       (current_state[0]));
  OR2X1 g2043__7410(.A (next_state[1]), .B (next_state[2]), .Y (n_4));
  INVXL g2045(.A (flick), .Y (n_29));
  BUFX2 drc_buf_sp2080(.A (next_state[0]), .Y (n_75));
  DFFRX1 \current_state_reg[2] (.RN (rst), .CK (clk), .D
       (next_state[2]), .Q (current_state[2]), .QN (n_0));
  DFFRX2 \LEDs_reg[5] (.RN (rst), .CK (clk), .D (n_36), .Q (LEDs[5]),
       .QN (n_2));
  DFFRX2 \LEDs_reg[10] (.RN (rst), .CK (clk), .D (n_39), .Q (LEDs[10]),
       .QN (n_12));
  DFFRX1 \current_state_reg[1] (.RN (rst), .CK (clk), .D
       (next_state[1]), .Q (current_state[1]), .QN (n_52));
  DFFRHQX1 \LEDs_reg[2] (.RN (rst), .CK (clk), .D (n_59), .Q (LEDs[2]));
  DFFRHQX1 \LEDs_reg[0] (.RN (rst), .CK (clk), .D (n_60), .Q (LEDs[0]));
  DFFRHQX1 \LEDs_reg[14] (.RN (rst), .CK (clk), .D (n_55), .Q
       (LEDs[14]));
  DFFRHQX1 \LEDs_reg[9] (.RN (rst), .CK (clk), .D (n_40), .Q (LEDs[9]));
  DFFRHQX1 \LEDs_reg[8] (.RN (rst), .CK (clk), .D (n_41), .Q (LEDs[8]));
  DFFRHQX1 \LEDs_reg[12] (.RN (rst), .CK (clk), .D (n_38), .Q
       (LEDs[12]));
  DFFRHQX1 \LEDs_reg[7] (.RN (rst), .CK (clk), .D (n_37), .Q (LEDs[7]));
  DFFRHQX1 \LEDs_reg[4] (.RN (rst), .CK (clk), .D (n_31), .Q (LEDs[4]));
  DFFRHQX1 \LEDs_reg[13] (.RN (rst), .CK (clk), .D (n_35), .Q
       (LEDs[13]));
  AO21X1 g2(.A0 (LEDs[14]), .A1 (n_75), .B0 (n_23), .Y (n_91));
  DFFRHQX1 \LEDs_reg[6] (.RN (rst), .CK (clk), .D (n_33), .Q (LEDs[6]));
  DFFRHQX1 \LEDs_reg[3] (.RN (rst), .CK (clk), .D (n_34), .Q (LEDs[3]));
  NOR2BX1 g2120(.AN (rst), .B (current_state[0]), .Y (n_92));
endmodule

